/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as AdnRouteRouteImport } from './routes/adn/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdnIndexRouteImport } from './routes/adn/index'
import { Route as AdnStudentRouteImport } from './routes/adn/student'
import { Route as AdnSettingsRouteImport } from './routes/adn/settings'
import { Route as AdnCoachRouteImport } from './routes/adn/coach'
import { Route as AdnAuthRouteImport } from './routes/adn/auth'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdnRouteRoute = AdnRouteRouteImport.update({
  id: '/adn',
  path: '/adn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdnIndexRoute = AdnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdnRouteRoute,
} as any)
const AdnStudentRoute = AdnStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AdnRouteRoute,
} as any)
const AdnSettingsRoute = AdnSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdnRouteRoute,
} as any)
const AdnCoachRoute = AdnCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AdnRouteRoute,
} as any)
const AdnAuthRoute = AdnAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AdnRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adn': typeof AdnRouteRouteWithChildren
  '/report': typeof ReportRoute
  '/adn/auth': typeof AdnAuthRoute
  '/adn/coach': typeof AdnCoachRoute
  '/adn/settings': typeof AdnSettingsRoute
  '/adn/student': typeof AdnStudentRoute
  '/adn/': typeof AdnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/adn/auth': typeof AdnAuthRoute
  '/adn/coach': typeof AdnCoachRoute
  '/adn/settings': typeof AdnSettingsRoute
  '/adn/student': typeof AdnStudentRoute
  '/adn': typeof AdnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adn': typeof AdnRouteRouteWithChildren
  '/report': typeof ReportRoute
  '/adn/auth': typeof AdnAuthRoute
  '/adn/coach': typeof AdnCoachRoute
  '/adn/settings': typeof AdnSettingsRoute
  '/adn/student': typeof AdnStudentRoute
  '/adn/': typeof AdnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adn'
    | '/report'
    | '/adn/auth'
    | '/adn/coach'
    | '/adn/settings'
    | '/adn/student'
    | '/adn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/report'
    | '/adn/auth'
    | '/adn/coach'
    | '/adn/settings'
    | '/adn/student'
    | '/adn'
  id:
    | '__root__'
    | '/'
    | '/adn'
    | '/report'
    | '/adn/auth'
    | '/adn/coach'
    | '/adn/settings'
    | '/adn/student'
    | '/adn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdnRouteRoute: typeof AdnRouteRouteWithChildren
  ReportRoute: typeof ReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adn': {
      id: '/adn'
      path: '/adn'
      fullPath: '/adn'
      preLoaderRoute: typeof AdnRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adn/': {
      id: '/adn/'
      path: '/'
      fullPath: '/adn/'
      preLoaderRoute: typeof AdnIndexRouteImport
      parentRoute: typeof AdnRouteRoute
    }
    '/adn/student': {
      id: '/adn/student'
      path: '/student'
      fullPath: '/adn/student'
      preLoaderRoute: typeof AdnStudentRouteImport
      parentRoute: typeof AdnRouteRoute
    }
    '/adn/settings': {
      id: '/adn/settings'
      path: '/settings'
      fullPath: '/adn/settings'
      preLoaderRoute: typeof AdnSettingsRouteImport
      parentRoute: typeof AdnRouteRoute
    }
    '/adn/coach': {
      id: '/adn/coach'
      path: '/coach'
      fullPath: '/adn/coach'
      preLoaderRoute: typeof AdnCoachRouteImport
      parentRoute: typeof AdnRouteRoute
    }
    '/adn/auth': {
      id: '/adn/auth'
      path: '/auth'
      fullPath: '/adn/auth'
      preLoaderRoute: typeof AdnAuthRouteImport
      parentRoute: typeof AdnRouteRoute
    }
  }
}

interface AdnRouteRouteChildren {
  AdnAuthRoute: typeof AdnAuthRoute
  AdnCoachRoute: typeof AdnCoachRoute
  AdnSettingsRoute: typeof AdnSettingsRoute
  AdnStudentRoute: typeof AdnStudentRoute
  AdnIndexRoute: typeof AdnIndexRoute
}

const AdnRouteRouteChildren: AdnRouteRouteChildren = {
  AdnAuthRoute: AdnAuthRoute,
  AdnCoachRoute: AdnCoachRoute,
  AdnSettingsRoute: AdnSettingsRoute,
  AdnStudentRoute: AdnStudentRoute,
  AdnIndexRoute: AdnIndexRoute,
}

const AdnRouteRouteWithChildren = AdnRouteRoute._addFileChildren(
  AdnRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdnRouteRoute: AdnRouteRouteWithChildren,
  ReportRoute: ReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
