/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as AdnRouteRouteImport } from './routes/adn/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdnIndexRouteImport } from './routes/adn/index'
import { Route as AdnAuthRouteImport } from './routes/adn/auth'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdnRouteRoute = AdnRouteRouteImport.update({
  id: '/adn',
  path: '/adn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdnIndexRoute = AdnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdnRouteRoute,
} as any)
const AdnAuthRoute = AdnAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AdnRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adn': typeof AdnRouteRouteWithChildren
  '/report': typeof ReportRoute
  '/adn/auth': typeof AdnAuthRoute
  '/adn/': typeof AdnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/adn/auth': typeof AdnAuthRoute
  '/adn': typeof AdnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adn': typeof AdnRouteRouteWithChildren
  '/report': typeof ReportRoute
  '/adn/auth': typeof AdnAuthRoute
  '/adn/': typeof AdnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adn' | '/report' | '/adn/auth' | '/adn/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/report' | '/adn/auth' | '/adn'
  id: '__root__' | '/' | '/adn' | '/report' | '/adn/auth' | '/adn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdnRouteRoute: typeof AdnRouteRouteWithChildren
  ReportRoute: typeof ReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adn': {
      id: '/adn'
      path: '/adn'
      fullPath: '/adn'
      preLoaderRoute: typeof AdnRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adn/': {
      id: '/adn/'
      path: '/'
      fullPath: '/adn/'
      preLoaderRoute: typeof AdnIndexRouteImport
      parentRoute: typeof AdnRouteRoute
    }
    '/adn/auth': {
      id: '/adn/auth'
      path: '/auth'
      fullPath: '/adn/auth'
      preLoaderRoute: typeof AdnAuthRouteImport
      parentRoute: typeof AdnRouteRoute
    }
  }
}

interface AdnRouteRouteChildren {
  AdnAuthRoute: typeof AdnAuthRoute
  AdnIndexRoute: typeof AdnIndexRoute
}

const AdnRouteRouteChildren: AdnRouteRouteChildren = {
  AdnAuthRoute: AdnAuthRoute,
  AdnIndexRoute: AdnIndexRoute,
}

const AdnRouteRouteWithChildren = AdnRouteRoute._addFileChildren(
  AdnRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdnRouteRoute: AdnRouteRouteWithChildren,
  ReportRoute: ReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
